name: Build and Run
 
on: 
    push:
        branches: [master]
 
jobs:
  build:
#    env:
#       Solution_Name: EnvironmentMonitoringSystem.sln
#       Test_Project_Path: EnvironmentMonitoringSystem\sender.Tests\sender.Tests.csproj
   
   runs-on: windows-latest
   steps:
    - uses: actions/checkout@v2

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
