name: Build and Run
 
on: 
    push:
        branches: [master]
 
jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug]
 
    runs-on: windows-latest

    env:
      Solution_Name: EnvironmentMonitoringSystem.sln
