name: Build and Run
 
on: 
    push:
        branches: [master]
 
jobs:
  build:
   env:
      Solution_Name: EnvironmentMonitoringSystem.sln
   
   runs-on: windows-latest
   steps:
    - uses: actions/checkout@v2

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Run tests
      run: dotnet test
